### ISSUE TITLE
Fetch and Display Sample Data

### ISSUE THREAD

**Issue by TeachMeTW** [TeachMeTW/CNN#5]
**Description:**

- Retrieve sample sensor data from the database and display it in the app.

**Tasks:**

- Write functions to query the database based on user selections.
- Display retrieved data in a table or chart.
- Handle exceptions and display error messages if data retrieval fails.

Reliant on #3 for fake data

**Comment by ptanshul** [comment]
please provide more details like sample data
Also I cannot find database .Please provide details

**Comment by TeachMeTW** [comment]
> please provide more details like sample data Also I cannot find database .Please provide details

@ptanshul The db and sample data are of your choosing; you can ask Jim for what sample data would look like -- I suggest doing #2 or #3 or if theres something I missed add it as a ticket
